# https://pre-commit.com/

repos:
  - repo: local
    hooks:
      - id: fix
        name: fix
        language: system
        files: '[.]rs$'
        entry: cargo fix --allow-staged
        pass_filenames: false

      - id: fmt
        name: fmt
        language: system
        files: '[.]rs$'
        entry: rustup run --install nightly-2020-06-04 rustfmt
        pass_filenames: true

      # Each package is checked separately because of
      # https://github.com/rust-lang/cargo/issues/5364

      - id: check:cope
        name: check:cope
        language: system
        files: '[.]rs$'
        entry: cargo clippy --manifest-path crates/cope/Cargo.toml --all-targets --features strict
        pass_filenames: false

      - id: check:cope-dom
        name: check:cope-dom
        language: system
        files: '[.]rs$'
        entry: cargo clippy --manifest-path crates/cope-dom/Cargo.toml --all-targets --features strict
        pass_filenames: false

      - id: check:example-cli-counter
        name: check:example-cli-counter
        language: system
        files: '[.]rs$'
        entry: cargo clippy --manifest-path crates/example-cli-counter/Cargo.toml --all-targets --features strict
        pass_filenames: false

      - id: check:example-web-counter
        name: check:example-web-counter
        language: system
        files: '[.]rs$'
        entry: cargo clippy --manifest-path crates/example-web-counter/Cargo.toml --all-targets --features strict
        pass_filenames: false

      - id: check:example-web-todo
        name: check:example-web-todo
        language: system
        files: '[.]rs$'
        entry: cargo clippy --manifest-path crates/example-web-todo/Cargo.toml --all-targets --features strict
        pass_filenames: false

      - id: check:js-framework-benchmark
        name: check:js-framework-benchmark
        language: system
        files: '[.]rs$'
        entry: cargo clippy --manifest-path crates/js-framework-benchmark/Cargo.toml --all-targets --features strict
        pass_filenames: false

      - id: test
        name: test
        language: system
        files: '[.]rs$'
        entry: cargo test
        pass_filenames: false
