[package]
name = "cope-example-cli-counter"
version = "0.0.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[features]
strict = []

[dependencies]
once_cell = "1.4.0"
parking_lot = "0.11.0"
